/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceUI;

import business.Patient;
import javax.swing.JOptionPane;

/**
 *Basic JFrame
 * @author Divyansh
 */
public class BaseJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BaseJFrame
     */
    Patient patient;

    public BaseJFrame() {
        initComponents();
        patient = new Patient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        createNewPatJButton = new javax.swing.JButton();
        viewpatientJButton = new javax.swing.JButton();
        addVitalJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        createNewPatJButton.setBackground(new java.awt.Color(255, 204, 204));
        createNewPatJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createNewPatJButton.setText("Create New Patient");
        createNewPatJButton.setMargin(new java.awt.Insets(2, 16, 2, 16));
        createNewPatJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewPatJButtonActionPerformed(evt);
            }
        });

        viewpatientJButton.setBackground(new java.awt.Color(255, 204, 204));
        viewpatientJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewpatientJButton.setText("View Patient Details");
        viewpatientJButton.setMargin(new java.awt.Insets(2, 16, 2, 16));
        viewpatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpatientJButtonActionPerformed(evt);
            }
        });

        addVitalJButton.setBackground(new java.awt.Color(255, 204, 204));
        addVitalJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addVitalJButton.setText("Add Vital Sign");
        addVitalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVitalJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createNewPatJButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewpatientJButton, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(addVitalJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(createNewPatJButton)
                .addGap(46, 46, 46)
                .addComponent(addVitalJButton)
                .addGap(47, 47, 47)
                .addComponent(viewpatientJButton)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        patientSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("PATIENT RECORD PORTAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );

        patientSplitPane.setRightComponent(jPanel2);

        getContentPane().add(patientSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createNewPatJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewPatJButtonActionPerformed
        // TODO add your handling code here:
        //
        if (patient.getName() != null) {
            int response = JOptionPane.showConfirmDialog(null, "Application will delete all existing patient. Continue?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                this.patient = null;
                this.patient = new Patient();
            } else {
                return;
            }
        }
        CreatePatientJPanel createNew = new CreatePatientJPanel(patient);
        patientSplitPane.setRightComponent(createNew);

    }//GEN-LAST:event_createNewPatJButtonActionPerformed

    private void addVitalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVitalJButtonActionPerformed
        // TODO add your handling code here:
        if (patient.getName() != null) {
            AddVitalInfoJPanel addVital = new AddVitalInfoJPanel(patient);
            patientSplitPane.setRightComponent(addVital);
        } else {
            //If clicked before creating any person
            JOptionPane.showMessageDialog(null, "No patient found !", "Create Patient", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addVitalJButtonActionPerformed

    private void viewpatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpatientJButtonActionPerformed
        // TODO add your handling code here:
        if (patient.getName() != null) {
            ViewPatientJPanel viewPanel = new ViewPatientJPanel(patient);
            patientSplitPane.setRightComponent(viewPanel);
        } else {
            //If clicked before creating any person
            JOptionPane.showMessageDialog(null, "No patient found !", "Create Patient", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_viewpatientJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVitalJButton;
    private javax.swing.JButton createNewPatJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane patientSplitPane;
    private javax.swing.JButton viewpatientJButton;
    // End of variables declaration//GEN-END:variables
}
